### ISSUE TITLE
I can't get Loras to work with your SDXL workflow

### ISSUE THREAD

**Issue by mattymatty** [GalaxyTimeMachine/GTM_ComfyUI_workflows#1]
I don't think the ComfyUI_tinyterra SDXL Pipeloader and Sampler properly handles Loras. Can you get Loras to work with your workflow?

**Comment by GalaxyTimeMachine** [comment]
You may need these: https://github.com/rgthree/rgthree-comfy

**Comment by GalaxyTimeMachine** [comment]
I've updated the repo, which includes the latest SDXL v5 workflow, just released.
